services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/movies
    depends_on:
      - db
    volumes:
      - .:/app # Para que as alterações no código sejam refletidas
      - /app/node_modules # Evitar conflito com o volume de dependências
    command: sh -c "npx prisma migrate deploy && npx prisma generate && yarn run dev" # Executa as migrações e inicia o servidor

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
